export const quotes = [
    { text: "Design is not just what it looks like and feels like. Design is how it works.", author: "Steve Jobs" },
    { text: "Creativity is intelligence having fun.", author: "Albert Einstein" },
    { text: "Good design is as little design as possible.", author: "Dieter Rams" },
    { text: "Design adds value faster than it adds costs.", author: "Joel Spolsky" },
    { text: "You can't use up creativity. The more you use, the more you have.", author: "Maya Angelou" },
    { text: "Creativity is seeing what everyone else has seen, and thinking what no one else has thought.", author: "Albert Einstein" },
    { text: "To create something exceptional, your mindset must be relentlessly focused on the smallest detail.", author: "Giorgio Armani" },
    { text: "Simplicity is the ultimate sophistication.", author: "Leonardo da Vinci" },
    { text: "Every great design begins with an even better story.", author: "Lorinda Mamo" },
    { text: "Design is where science and art break even.", author: "Robin Mathew" },
    { text: "The best way to predict the future is to create it.", author: "Peter Drucker" },
    { text: "If you think good design is expensive, you should look at the cost of bad design.", author: "Ralf Speth" },
    { text: "An essential aspect of creativity is not being afraid to fail.", author: "Edwin Land" },
    { text: "Design is thinking made visual.", author: "Saul Bass" },
    { text: "There is no design without discipline. There is no discipline without intelligence.", author: "Massimo Vignelli" },
    { text: "Creativity doesn't wait for that perfect moment. It fashions its own perfect moments out of ordinary ones.", author: "Bruce Garrabrandt" },
    { text: "Design should never say, 'Look at me.' It should always say, 'Look at this.'", author: "David Craib" },
    { text: "Innovation is the outcome of a habit, not a random act.", author: "Sukant Ratnakar" },
    { text: "The details are not the details. They make the design.", author: "Charles Eames" },
    { text: "Art is the most intense mode of individualism that the world has known.", author: "Oscar Wilde" },
    { text: "Design is a solution to a problem. Art is a question to a problem.", author: "John Maeda" },
    { text: "Make it simple, but significant.", author: "Don Draper" },
    { text: "The creative adult is the child who survived.", author: "Ursula K. Le Guin" },
    { text: "Creativity takes courage.", author: "Henri Matisse" },
    { text: "The role of the designer is that of a good, thoughtful host anticipating the needs of his guests.", author: "Charles Eames" },
    { text: "Design must reflect the practical and aesthetic in business but above all... good design must primarily serve people.", author: "Thomas J. Watson" },
    { text: "Typography is the craft of endowing human language with a durable visual form.", author: "Robert Bringhurst" },
    { text: "The best ideas emerge when very different perspectives meet.", author: "Frans Johansson" },
    { text: "The heart and soul of the company is creativity and innovation.", author: "Bob Iger" },
    { text: "Creativity is allowing yourself to make mistakes. Design is knowing which ones to keep.", author: "Scott Adams" },
    { text: "Digital design is like painting, except the paint never dries.", author: "Neville Brody" },
    { text: "Design is the intermediary between information and understanding.", author: "Richard Grefé" },
    { text: "It's through mistakes that you actually can grow. You have to get bad in order to get good.", author: "Paula Scher" },
    { text: "A designer knows he has achieved perfection not when there is nothing left to add, but when there is nothing left to take away.", author: "Antoine de Saint-Exupéry" },
    { text: "Design is intelligence made visible.", author: "Alina Wheeler" },
    { text: "Simplicity is about subtracting the obvious and adding the meaningful.", author: "John Maeda" },
    { text: "There's no shortage of remarkable ideas, what's missing is the will to execute them.", author: "Seth Godin" },
    { text: "Design creates culture. Culture shapes values. Values determine the future.", author: "Robert L. Peters" },
    { text: "Design is not for philosophy, it's for life.", author: "Issey Miyake" },
    { text: "Creativity involves breaking out of established patterns in order to look at things in a different way.", author: "Edward de Bono" },
    { text: "The essence of design lies in clarity and simplicity.", author: "Lindon Leader" },
    { text: "An idea that is not dangerous is unworthy of being called an idea at all.", author: "Oscar Wilde" },
    { text: "Design isn't finished until somebody is using it.", author: "Brenda Laurel" },
    { text: "The real issue is not talent as an independent element, but talent in relationship to will, desire, and persistence.", author: "Milton Glaser" },
    { text: "Good design begins with honesty, asks tough questions, comes from collaboration and from trusting your intuition.", author: "Freeman Thomas" },
    { text: "A designer is an emerging synthesis of artist, inventor, mechanic, objective economist, and evolutionary strategist.", author: "R. Buckminster Fuller" },
    { text: "Design is not a single object or dimension. Design is messy and complex.", author: "Natasha Jen" },
    { text: "Life begins at the end of your comfort zone.", author: "Anonymous" },
    { text: "Every sunset is an opportunity to reset.", author: "Anonymous" },
    { text: "The best view comes after the hardest climb.", author: "Anonymous" },
    { text: "Your life is your message to the world.", author: "Anonymous" },
    { text: "In the end, we only regret the chances we didn't take.", author: "Anonymous" },
    { text: "Life is short, but your smile can last forever.", author: "Anonymous" },
    { text: "The little things in life matter the most.", author: "Anonymous" },
    { text: "Your story isn't over yet.", author: "Anonymous" },
    { text: "Stars can't shine without darkness.", author: "Anonymous" },
    { text: "Life is tough, but so are you.", author: "Anonymous" },
    { text: "Every day is a second chance.", author: "Anonymous" },
    { text: "Kindness is free, sprinkle it everywhere.", author: "Anonymous" },
    { text: "Be the reason someone believes in good people.", author: "Anonymous" },
    { text: "Life is art. Live yours in color.", author: "Anonymous" },
    { text: "The best time for new beginnings is now.", author: "Anonymous" }
]; 